### ISSUE TITLE
Kickstart issue

### ISSUE THREAD

**Issue by torkildl** [arnaud-carre/ldos#2]
I have noticed that my own demo demo-in-progress does not load, but ends in LDOS debug screen, it is started under AROS and not ordinary Kickstart. I checked with another LDOS product, and the same thing happens. If I load older ADF trackmos under AROS, there is no issue.

Maybe it is possible to fix this, to increase compatibility? Certainly not a big issue, but one nevertheless. :)

**Comment by arnaud-carre** [comment]
Hi! yes I'm aware of this AROS issue and I don't know why other demos are working. The issue is that AROS at boot time returns very few bytes left regarding fake memory ( like something like 200 bytes left instead of about 500KiB ). 
What other ADF trackload demo is working? Is that a 1MiB demo or just 512KiB demo?

**Comment by torkildl** [comment]
Ok, then I understand. I tested some old demos, and they conformed to this expectation. I know that Sanity's old stuff (e.g. Elysium) only required a 512K A500 and that worked out in AROS.

**Comment by arnaud-carre** [comment]
yeah I suspect most of 1MiB demo to *not* boot using AROS. To me it's AROS bug ( or maybe AROS really need such large amount of memory when booting )
